# Generated by Django 5.1.6 on 2025-07-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
