# Generated by Django 5.1.6 on 2025-07-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
